os:
  - osx
language: 
  - objective-c
compiler:
  - clang
before_install:
  - brew update
install:
  - brew install cmake
  - brew install boost-python
before_script:
  - git clone https://github.com/audiofilter/spuclib.git
  - cd spuclib
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - mkdir build
  - cd build
  - cmake ../extensions
script: make
