language: 
  - cpp 
compiler:
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake libboost-dev
before_script:
  - git clone https://github.com/audiofilter/spuc.git
  - mkdir build
  - cd build
  - cmake ../extensions
script: make
